# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          JulyPAPA's Blog
paginate:       5
baseurl:        "/julypapa-blog/"
url:            "https://nakniner.github.io/julypapa-blog"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Jonghoon, Lee
  url:          http://nakniner.github.io
  email:        nakniner@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/nakniner/julypapa-blog

# Gems
gems:
  - jekyll-paginate

# SNS icon
social:
- {icon: 'github', link: 'https://www.github.com/nakniner'}
- {icon: 'twitter', link: 'https://twitter.com/nakniner'}
- {icon: 'instagram', link: 'https://instagram.com/nakniner'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/jong-hoon-lee-9434a6133/'}
- {icon: 'envelope', link: 'mailto:nakniner@gmail.com'}
- {icon: 'rss-square', link: 'https://www.github.com/nakniner/feed.xml'}
